### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-html-atom-and-basic-elements-JmL5o8#1]
@egillespie Can you take a look at this? It's [hosted here](https://GriffinMartin.github.io/MI-449-SS17-740-html-atom-and-basic-elements-JmL5o8/) and meets the following criteria:

- [x] Each of the following elements is used appropriately, at least once: `h1`, `h2`, `p`, `img`, `li`, `a`
- [x] At least one of the following elements is used: `ol`, `ul`
- [x] At least one external image is used and links to the page it came from

I'm very excited for this semester! I wish more classes were structured like this.

**Comment by egillespie** [comment]
@GriffinMartin Looking good so far! You're missing an `a` element. I recommend using it around your image to satisfy the third criteria (and kill two birds with one stone).

When you've pushed that change to `master` and `gh-pages`, @mention me in a comment here and I'll take another look.

Thanks for the kind words! We're also super excited about this semester and really hope everyone gets a lot out of the lessons. :smile:

**Comment by GriffinMartin** [comment]
@egillespie Fixed it up! Thanks for the quick feedback =)

**Comment by egillespie** [comment]
Great work! :shipit: 

One small note: the only elements allowed between `<html>` tags are `<head>` and `<body>`. If you want a footer, you'll want to put the `<footer>` tags inside your `<body>`.
